/* =============================================================================
 *  tools/solve-linkage.js — find the φ/ψ that build a real polysaccharide
 * =============================================================================
 *  Offline, dependency-free.  node tools/solve-linkage.js
 *
 *  THE PROBLEM THIS SOLVES. maltose and cellobiose need real torsions about the
 *  glycosidic bond, and typing them is the one thing that must not happen here.
 *  Published φ/ψ come in at least three conventions (heavy-atom O5–C1–O1–C4′ vs
 *  the hydrogen-referenced H1–C1–O1–C4′, and sign conventions differ), so a
 *  number copied without its convention is a claim that looks precise and is
 *  unfalsifiable. chain/glucose-chains-test.html is the record of what happens
 *  without them: cellulose comes out right by luck and starch draws as a ribbon.
 *
 *  SO THE TORSION IS DERIVED, NOT QUOTED. What gets cited instead is the thing a
 *  textbook states unambiguously and a checker can measure: the HELIX the
 *  polymer forms. Repeat the linkage and you get a screw; search φ/ψ for the
 *  pair whose screw matches the published residues-per-turn and rise. The
 *  torsions come out as a consequence, in whatever convention this builder uses,
 *  and no convention has to be guessed.
 *
 *  This is the same shape of argument as tools/bake-flat2d.js: a derived field,
 *  regenerated by a tool, checked against the source it came from.
 *
 *  Prints the values to paste. `--write` is deliberately NOT implemented — the
 *  two numbers land in a builder call a human should read in context, and
 *  tools/specfile.js writes FIELDS, not arguments.
 * ========================================================================== */
'use strict';

const path = require('path');
const CR = require(path.join(__dirname, '../chain-repeat.js'));
const { MolLib } = require(path.join(__dirname, '../molecules.js'));
require(path.join(__dirname, '../skel.js'));
require(path.join(__dirname, '../mol-monomers.js'));
require(path.join(__dirname, '../mol-pathways.js'));
require(path.join(__dirname, '../mol-contrast.js'));

/* The builder hands back RAW ångströms — register() is what multiplies by
 * SCALE, and nothing here goes through it. Dividing by SCALE anyway (as the
 * first version did) under-reports every rise by 1.9×, which quietly moved both
 * targets and made a wrong linkage look like a perfect fit. */
const build = MolLib.BUILD && MolLib.BUILD.disaccharide;
if (!build) { console.log('FAIL: mol-contrast.js did not expose BUILD.disaccharide'); process.exit(1); }

/* The published targets. These are the citation — everything else is derived.
 * Rise is per RESIDUE, in ångströms.
 *
 *   Cellulose Iβ   two-fold ribbon; the cellobiose repeat is ~10.3–10.4 Å, so a
 *                  glucose rises ~5.2 Å and turns 180°.
 *   V-amylose      six residues per turn with a pitch near 8 Å, so a glucose
 *                  turns 60° and rises ~1.33 Å.
 *
 * Both are the standard figures a biochemistry text gives for these polymers,
 * and both are what chain/check-chain.js re-measures off the built spec. */
const TARGETS = {
  cellobiose: { alpha:false, perTurn:2, rise:5.20, name:'cellulose Iβ' },
  maltose:    { alpha:true,  perTurn:6, rise:1.33, name:'V-amylose' },
};

const TRIAD = ['O5','C1','C4'];
const D = 180/Math.PI, R = Math.PI/180;

// A spec built at these torsions, named the way chain-repeat expects.
function specAt(alpha, phi, spin){
  const b = build(alpha, { phi, spin });
  return b.s.spec({
    name:'probe', formula:'C₁₂H₂₂O₁₁', class:'sugar',
    names:['O5A','C1A','C2A','C3A','C4A','C5A','O1A','O2A','HO2A','O3A','HO3A','O4A','HO4A','C6A','O6A','HO6A','H1A','H2A','H3A','H4A','H5A','H61A','H62A','O5B','C1B','C2B','C3B','C4B','C5B','H4B','O1B','HO1B','O2B','HO2B','O3B','HO3B','C6B','O6B','HO6B','H1B','H2B','H3B','H5B','H61B','H62B'],
  });
}

// How far a built linkage lands from its target helix. Turn and rise are in
// different units, so each is scored as a fraction of its own target.
/* Clearance to aim for. Deliberately modest, because palette.js's radii are
 * "stylised — enlarged for legibility", not van der Waals: two atoms this
 * library draws as nearly touching are comfortably apart in the real molecule.
 * So crowding here is a RENDERING constraint, and letting it outvote the helix
 * would be choosing a prettier picture over the right polymer. */
const ROOMY = 0.15;
function costOf(t, screw, clear){
  const turn = Math.abs(screw.perTurn - t.perTurn) / t.perTurn;
  const rise = Math.abs(screw.rise - t.rise) / t.rise;
  /* Clearing the checker's floor is not the same as being a plausible
   * conformation. A pose with 0.03 to spare satisfies every assertion here and
   * still has two atoms all but touching — the committed schematic sits at 0.64
   * and reads cleanly. So crowding is a soft cost: among linkages that hit the
   * helix, prefer the one with room. */
  const tight = Math.max(0, ROOMY - clear) / ROOMY;
  return turn + rise + 0.3*tight;
}

// Clashes matter: a torsion that threads the two rings through each other would
// score beautifully and be nonsense. Reuse the floor check-molecules.js applies.
function worstOverlap(spec){
  const P=MolLib.PALETTE, bonded=new Set();
  (spec.bonds||[]).forEach(([i,j])=>bonded.add(i<j?`${i},${j}`:`${j},${i}`));
  let worst=Infinity;
  for(let i=0;i<spec.atoms.length;i++)
    for(let j=i+1;j<spec.atoms.length;j++){
      if(bonded.has(`${i},${j}`)) continue;
      const a=spec.atoms[i], b=spec.atoms[j];
      const d=Math.hypot(a.pos[0]-b.pos[0], a.pos[1]-b.pos[1], a.pos[2]-b.pos[2]);
      const need=(P.radii[a.el]||0.7)+(P.radii[b.el]||0.7);
      worst=Math.min(worst, d-need);
    }
  return worst;
}

for (const [key, t] of Object.entries(TARGETS)) {
  let best=null;
  // coarse sweep, then refine around the winner
  const scan=(p0,p1,s0,s1,step)=>{
    for(let phi=p0; phi<=p1; phi+=step)
      for(let spin=s0; spin<=s1; spin+=step){
        let spec, screw;
        try {
          spec=specAt(t.alpha, phi*R, spin*R);
          screw=CR.screwOf(spec, TRIAD, 'A', 'B');
        } catch(e){ continue; }
        if(!isFinite(screw.perTurn)) continue;
        const clear=worstOverlap(spec);
        // The floor is check-molecules.js's own: spheres must not merge. A
        // stricter one here silently discards conformations the library
        // considers perfectly legal, which is how the first run rejected a
        // better cellulose than the one it returned.
        if(clear < 0.02) continue;
        const c=costOf(t, screw, clear);
        if(!best || c<best.cost) best={cost:c, phi, spin, screw, clear};
      }
  };
  scan(-180,180,-180,180,5);
  if(best) scan(best.phi-6, best.phi+6, best.spin-6, best.spin+6, 0.5);

  console.log(`\n== ${key} → ${t.name}`);
  if(!best){ console.log('   no clash-free linkage reproduces this helix'); continue; }
  console.log(`   target      ${t.perTurn} residues/turn, ${t.rise.toFixed(2)} Å rise`);
  console.log(`   built       ${best.screw.perTurn.toFixed(2)} residues/turn, `
    + `${best.screw.rise.toFixed(2)} Å rise`);
  console.log(`   clearance   ${best.clear.toFixed(2)} (checker floor is 0)`);
  console.log(`   cost        ${best.cost.toFixed(3)} (helix + crowding)`);
  console.log(`   PASTE  { phi:${best.phi.toFixed(1)}*Math.PI/180, `
    + `spin:${best.spin.toFixed(1)}*Math.PI/180 }`);
}
