#!/usr/bin/env node
/* =====================================================================
 *  fold2pdb.js — the baked villin fold, as a multi-MODEL PDB.
 *
 *  STAGE 0 of the Mol* evaluation (docs/ToDo.md item 2). Mol* reads a
 *  multi-MODEL PDB as a trajectory natively, so this is the bridge between
 *  our solver's output and any viewer that is not ours.
 *
 *  It is worth having even if Mol* is rejected: `folding/data/1VII.fold.bin`
 *  is a private Float32 format that only `folding.js` can read, and the only
 *  thing that currently checks it is the code that wrote it. Exporting to
 *  PDB makes the trajectory inspectable in VMD, PyMOL, ChimeraX or Mol* —
 *  an outside opinion on a file we otherwise grade ourselves.
 *
 *  IT ADDS NO SCIENCE. Every coordinate here came out of the committed
 *  bake unchanged; this is a format conversion, not a second source of
 *  truth. If it ever disagrees with the .bin, the .bin is right.
 *
 *  Atom identity comes from re-parsing 1VII.pdb with the SAME sideChains
 *  set bake-fold.js used — the trajectory stores bare xyz in parse() order
 *  and nothing else, so a different set here would silently mislabel every
 *  atom rather than fail.
 *
 *  Run:  node molstar/tools/fold2pdb.js [--stride N]
 *          --stride N   keep every Nth keyframe (default 1 = all)
 *
 *  Offline, no dependencies.
 * ===================================================================== */
'use strict';

const fs = require('fs');
const path = require('path');
const FoldLib = require('../../folding/folding.js');

const HERE = path.join(__dirname, '..');            // demos/molstar
const FOLD = path.join(HERE, '..', 'folding');      // demos/folding
const SRC = path.join(FOLD, 'data', '1VII.pdb');
const BIN = path.join(FOLD, 'data', '1VII.fold.bin');
const OUT = path.join(HERE, 'data', '1VII.fold.pdb');

/* Must match bake-fold.js's CORE_RESIDUES. Not a copy for convenience — the
   .bin has no atom names in it, so this list IS the decoding key. */
const CORE_RESIDUES = [47, 51, 58];

const strideArg = process.argv.indexOf('--stride');
const STRIDE = strideArg > -1 ? Math.max(1, parseInt(process.argv[strideArg + 1], 10) || 1) : 1;

for (const f of [SRC, BIN]) {
  if (!fs.existsSync(f)) { console.error('missing ' + path.relative(HERE, f)); process.exit(1); }
}

const parsed = FoldLib.parse(fs.readFileSync(SRC, 'utf8'), { sideChains: CORE_RESIDUES });
const bin = fs.readFileSync(BIN);
const traj = FoldLib.decode(bin.buffer.slice(bin.byteOffset, bin.byteOffset + bin.byteLength));

/* The one assertion that matters: the trajectory's atom count must match the
   atom list we just parsed. If it does not, CORE_RESIDUES has drifted from
   bake-fold.js and every label below would be wrong but plausible. */
if (traj.atoms !== parsed.nodes.length) {
  console.error(`atom count mismatch: .bin has ${traj.atoms}, parsing 1VII.pdb with ` +
                `sideChains [${CORE_RESIDUES}] gives ${parsed.nodes.length}.`);
  console.error('CORE_RESIDUES here must match folding/tools/bake-fold.js.');
  process.exit(1);
}

/* PDB fixed-column ATOM record. Atom names are column-sensitive: a one-letter
   element starts in column 14, which is what puts " CA " and "CA  " (calcium)
   in different places. Every name here is one-letter-element, so all indent. */
const pad = (s, n) => String(s).padStart(n);
function atomLine(serial, node, xyz) {
  const name = node.name.length >= 4 ? node.name : ' ' + node.name.padEnd(3);
  return 'ATOM  ' + pad(serial, 5) + ' ' + name + ' ' +
         node.resName.padEnd(3) + ' A' + pad(node.res, 4) + '    ' +
         pad(xyz[0].toFixed(3), 8) + pad(xyz[1].toFixed(3), 8) + pad(xyz[2].toFixed(3), 8) +
         '  1.00  0.00' + ' '.repeat(10) + pad(node.el, 2);
}

const out = [];
out.push('REMARK   1 VILLIN HEADPIECE HP35 (PDB 1VII) — BAKED FOLDING TRAJECTORY');
out.push('REMARK   1 GENERATED BY molstar/tools/fold2pdb.js FROM folding/data/1VII.fold.bin');
out.push('REMARK   1 THESE ARE SOLVER OUTPUT, NOT EXPERIMENTAL COORDINATES.');
out.push('REMARK   1 THE DEPOSITED STRUCTURE IS THE LAST FRAME ONLY; ALL OTHERS ARE');
out.push('REMARK   1 A CONSTRAINED RELAXATION AND HAVE NO EXPERIMENTAL BASIS.');
out.push(`REMARK   1 SIDE CHAINS RETAINED: ${CORE_RESIDUES.join(', ')} (HYDROPHOBIC CORE)`);

let model = 0;
for (let k = 0; k < traj.count; k += STRIDE) {
  const frame = traj.key[k];
  out.push('MODEL ' + pad(++model, 8));
  parsed.nodes.forEach((node, i) => {
    out.push(atomLine(i + 1, node, [frame[i*3], frame[i*3 + 1], frame[i*3 + 2]]));
  });
  out.push('ENDMDL');
}
out.push('END');

fs.mkdirSync(path.dirname(OUT), { recursive: true });
const text = out.join('\n') + '\n';
fs.writeFileSync(OUT, text);

console.log(`read ${traj.count} keyframes x ${traj.atoms} atoms from 1VII.fold.bin`);
console.log(`wrote ${model} models${STRIDE > 1 ? ` (stride ${STRIDE})` : ''} to ` +
            `${path.relative(path.join(HERE, '..'), OUT)} (${(text.length / 1024 / 1024).toFixed(2)} MB)`);
