/* =====================================================================
 *  residues.js — the twenty standard amino acid side chains.
 *
 *  GENERATED by tools/bake-residues.js. Do not edit: re-run the baker.
 *  tools/check-residues.js re-derives this file and fails if it is stale,
 *  and separately asserts the chemistry (L-configuration, ring closure,
 *  bond lengths, the textbook atom count of every type).
 *
 *  ResidueLib.SIDE[type] = { src, n, atoms, bonds, anchors }
 *    atoms    [name, element, x, y, z]  heavy atoms, side chain only
 *    bonds    [i, j] into atoms
 *    anchors  [i, 'CA'|'N'] where the side chain joins the backbone
 *    src      the structure it was measured from
 *    n        how many copies of this type that structure held
 *
 *  ResidueLib.graft(type, N, CA, C) -> [{name, el, p:[x,y,z]}]
 *    the side chain placed on one residue's backbone, in that backbone's
 *    own coordinates. Real ångströms — like folding/ and hemoglobin/, and
 *    unlike the MolLib specs, this never sees MolLib.SCALE.
 *
 *  COORDINATES ARE IN THE RESIDUE'S OWN N-CA-C FRAME: origin at CA, x
 *  along CA->C, z out of the N-CA-C plane. So a graft is one rigid
 *  transform, with no torsions and so no sign convention to invert — the
 *  handedness is inherited from the deposited structure it was measured
 *  from, and asserted by the checker.
 *
 *  EACH SIDE CHAIN IS ONE REAL CONFORMATION, the most typical copy in its
 *  source structure, NOT an average of them — see the baker's header for
 *  why an averaged rotamer is a shape no protein is ever in. It is one
 *  rotamer of several a real residue visits, so it is honest about
 *  CONNECTIVITY (which atoms, bonded how — the thing a lesson teaches)
 *  and representative, not canonical, about conformation.
 *
 *  Glycine is in the table with an empty atom list. That is not a gap: a
 *  hydrogen is all glycine has, and this file holds heavy atoms.
 * ===================================================================== */
(function (global) {
  'use strict';

  const SIDE = {
  ALA: { src:'2HHB', n:72,
    atoms:[['CB','C',-0.519,-0.762,-1.215]],
    bonds:[], anchors:[[0,'CA']] },
  ARG: { src:'2HHB', n:12,
    atoms:[['CB','C',-0.492,-0.705,-1.283], ['CG','C',-2.007,-0.923,-1.19], ['CD','C',-2.687,-1.057,-2.564], ['NE','N',-4.074,-1.527,-2.411], ['CZ','C',-4.688,-2.145,-3.467], ['NH1','N',-4.158,-2.072,-4.731], ['NH2','N',-5.863,-2.789,-3.254]],
    bonds:[[0,1],[1,2],[2,3],[3,4],[4,5],[4,6]], anchors:[[0,'CA']] },
  ASN: { src:'2HHB', n:20,
    atoms:[['CB','C',-0.297,-0.737,-1.29], ['CG','C',-1.752,-1.137,-1.191], ['OD1','O',-2.256,-1.255,-0.078], ['ND2','N',-2.423,-1.325,-2.323]],
    bonds:[[0,1],[1,2],[1,3]], anchors:[[0,'CA']] },
  ASP: { src:'2HHB', n:30,
    atoms:[['CB','C',-0.442,-0.763,-1.232], ['CG','C',-1.922,-1.113,-1.241], ['OD1','O',-2.499,-1.035,-0.152], ['OD2','O',-2.469,-1.428,-2.325]],
    bonds:[[0,1],[1,2],[1,3]], anchors:[[0,'CA']] },
  CYS: { src:'2HHB', n:6,
    atoms:[['CB','C',-0.495,-0.818,-1.152], ['SG','S',-2.163,-1.337,-0.749]],
    bonds:[[0,1]], anchors:[[0,'CA']] },
  GLN: { src:'2HHB', n:8,
    atoms:[['CB','C',-0.525,-0.777,-1.209], ['CG','C',-1.972,-1.197,-1.064], ['CD','C',-2.44,-1.918,-2.33], ['OE1','O',-2.407,-1.337,-3.413], ['NE2','N',-2.837,-3.179,-2.188]],
    bonds:[[0,1],[1,2],[2,3],[2,4]], anchors:[[0,'CA']] },
  GLU: { src:'2HHB', n:24,
    atoms:[['CB','C',-0.564,-0.63,-1.282], ['CG','C',-0.678,-2.109,-1.17], ['CD','C',-1.091,-2.537,-2.591], ['OE1','O',-0.325,-3.32,-3.16], ['OE2','O',-2.064,-1.987,-3.135]],
    bonds:[[0,1],[1,2],[2,3],[2,4]], anchors:[[0,'CA']] },
  GLY: { src:'2HHB', n:40,
    atoms:[],
    bonds:[], anchors:[] },
  HIS: { src:'2HHB', n:38,
    atoms:[['CB','C',-0.333,-0.764,-1.266], ['CG','C',-1.435,-1.756,-1.019], ['ND1','N',-2.729,-1.314,-0.578], ['CD2','C',-1.393,-3.143,-1.15], ['CE1','C',-3.531,-2.481,-0.451], ['NE2','N',-2.706,-3.613,-0.81]],
    bonds:[[0,1],[1,2],[1,3],[2,4],[3,5],[4,5]], anchors:[[0,'CA']] },
  ILE: { src:'9ZZI', n:150,
    atoms:[['CB','C',-0.555,-0.785,-1.205], ['CG1','C',-2.076,-0.885,-1.133], ['CG2','C',0.055,-2.178,-1.276], ['CD1','C',-2.673,-1.569,-2.318]],
    bonds:[[0,1],[0,2],[1,3]], anchors:[[0,'CA']] },
  LEU: { src:'2HHB', n:72,
    atoms:[['CB','C',-0.51,-0.761,-1.24], ['CG','C',-1.963,-1.062,-1.149], ['CD1','C',-2.397,-1.678,-2.44], ['CD2','C',-2.277,-1.974,0.009]],
    bonds:[[0,1],[1,2],[1,3]], anchors:[[0,'CA']] },
  LYS: { src:'2HHB', n:44,
    atoms:[['CB','C',-0.526,-0.747,-1.176], ['CG','C',-2.005,-1.099,-1.009], ['CD','C',-2.367,-1.879,-2.241], ['CE','C',-3.844,-2.222,-2.311], ['NZ','N',-3.984,-3.012,-3.553]],
    bonds:[[0,1],[1,2],[2,3],[3,4]], anchors:[[0,'CA']] },
  MET: { src:'2HHB', n:6,
    atoms:[['CB','C',-0.543,-0.815,-1.175], ['CG','C',-1.887,-1.461,-0.886], ['SD','S',-2.234,-2.737,-2.162], ['CE','C',-2.286,-1.7,-3.625]],
    bonds:[[0,1],[1,2],[2,3]], anchors:[[0,'CA']] },
  PHE: { src:'2HHB', n:30,
    atoms:[['CB','C',-0.493,-0.773,-1.241], ['CG','C',-1.944,-1.231,-1.034], ['CD1','C',-2.982,-0.605,-1.714], ['CD2','C',-2.222,-2.271,-0.172], ['CE1','C',-4.318,-1.006,-1.507], ['CE2','C',-3.534,-2.674,0.042], ['CZ','C',-4.59,-2.037,-0.628]],
    bonds:[[0,1],[1,2],[1,3],[2,4],[3,5],[4,6],[5,6]], anchors:[[0,'CA']] },
  PRO: { src:'2HHB', n:28,
    atoms:[['CB','C',-0.532,-0.7,-1.233], ['CG','C',-1.443,0.269,-1.924], ['CD','C',-1.49,1.528,-1.082]],
    bonds:[[0,1],[1,2]], anchors:[[0,'CA'],[2,'N']] },
  SER: { src:'2HHB', n:32,
    atoms:[['CB','C',-0.399,-0.731,-1.287], ['OG','O',-1.754,-1.082,-1.19]],
    bonds:[[0,1]], anchors:[[0,'CA']] },
  THR: { src:'2HHB', n:32,
    atoms:[['CB','C',-0.495,-0.724,-1.237], ['OG1','O',-0.106,-0.098,-2.414], ['CG2','C',-1.999,-0.912,-1.298]],
    bonds:[[0,1],[0,2]], anchors:[[0,'CA']] },
  TRP: { src:'2HHB', n:6,
    atoms:[['CB','C',-0.635,-0.667,-1.235], ['CG','C',-0.499,-2.167,-1.157], ['CD1','C',0.447,-2.995,-1.8], ['CD2','C',-1.311,-3.018,-0.389], ['NE1','N',0.205,-4.338,-1.431], ['CE2','C',-0.838,-4.352,-0.574], ['CE3','C',-2.376,-2.761,0.445], ['CZ2','C',-1.371,-5.453,0.054], ['CZ3','C',-2.925,-3.88,1.083], ['CH2','C',-2.428,-5.183,0.899]],
    bonds:[[0,1],[1,2],[1,3],[2,4],[3,5],[3,6],[4,5],[5,7],[6,8],[7,9],[8,9]], anchors:[[0,'CA']] },
  TYR: { src:'2HHB', n:12,
    atoms:[['CB','C',-0.544,-0.761,-1.223], ['CG','C',-1.968,-1.3,-1.006], ['CD1','C',-2.217,-2.661,-0.944], ['CD2','C',-3.007,-0.409,-0.85], ['CE1','C',-3.474,-3.149,-0.744], ['CE2','C',-4.302,-0.892,-0.643], ['CZ','C',-4.535,-2.258,-0.593], ['OH','O',-5.834,-2.749,-0.404]],
    bonds:[[0,1],[1,2],[1,3],[2,4],[3,5],[4,6],[5,6],[6,7]], anchors:[[0,'CA']] },
  VAL: { src:'2HHB', n:62,
    atoms:[['CB','C',-0.526,-0.739,-1.235], ['CG1','C',0.176,-2.061,-1.464], ['CG2','C',-2.036,-0.99,-1.069]],
    bonds:[[0,1],[0,2]], anchors:[[0,'CA']] },
  };

  /* Place a side chain on a backbone. N/CA/C are [x,y,z] in whatever
     coordinates the caller is working in; the result comes back in those
     same coordinates. */
  function graft(type, N, CA, C) {
    const r = SIDE[type];
    if (!r) throw new Error('residues.js has no side chain for ' + type);
    const sub = (a, b) => [a[0]-b[0], a[1]-b[1], a[2]-b[2]];
    const cross = (a, b) => [a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0]];
    const norm = a => { const n = Math.hypot(a[0], a[1], a[2]); return [a[0]/n, a[1]/n, a[2]/n]; };
    const x = norm(sub(C, CA));
    const z = norm(cross(x, sub(N, CA)));
    const y = cross(z, x);
    return r.atoms.map(([name, el, ax, ay, az]) => ({
      name, el,
      p: [CA[0] + x[0]*ax + y[0]*ay + z[0]*az,
          CA[1] + x[1]*ax + y[1]*ay + z[1]*az,
          CA[2] + x[2]*ax + y[2]*ay + z[2]*az],
    }));
  }

  const TYPES = Object.keys(SIDE);

  global.ResidueLib = { SIDE, TYPES, graft };
  if (typeof module !== 'undefined' && module.exports) module.exports = global.ResidueLib;
})(typeof globalThis !== 'undefined' ? globalThis : this);
